#!/usr/bin/env python3
"""
Generate paste/<screen>.controls.yaml from Src/<screen>.pa.yaml.

Power Apps Studio's Code View paste expects a TOP-LEVEL LIST OF CONTROLS on the
clipboard, not the `Screens:` document that .pa.yaml (pack/unpack) format uses.
This strips the wrapper and normalises the result to what the deserializer
accepts:

  Src/scrX.pa.yaml                     paste/scrX.controls.yaml
  --------------------------------     -------------------------------
  Screens:                             - conRoot:
    scrX:                                  Control: GroupContainer@1.5.0
      Properties:            ---->         ...
        Fill: =...                     - conSomeOverlay:
      Children:                            ...
        - conRoot:
            Control: ...

Three transformations, all required:

  1. Drop everything up to and including the screen's `Children:` line. Screen
     PROPERTIES (Fill, OnVisible) are NOT carried by a control paste - they must
     be set by hand in Studio. See paste/HOW-TO-PASTE.md.
  2. Dedent by 6 spaces so the first control sits at column 0.
  3. Strip `#` comments and blank lines. Studio's YAML parser rejects them with
     `PA1001 ... YamlInvalidSyntax`. The Src files keep their comments for Git.

It also writes paste/admin-rebuild.powerfx: the admin data build, lifted
from btnRefreshOverview.OnSelect on scrOverview (btnRefreshSubs on
scrSubmissions carries the same text - tools/scan_paste.py checks). Use it
if either button's formula ever has to be re-pasted by hand.

Usage:  python3 tools/gen_paste.py scrLanding
        python3 tools/gen_paste.py            # all screens
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "Src")
OUT = os.path.join(ROOT, "paste")

SCREENS = [
    "scrLanding", "scrForm", "scrDetail", "scrReview",
    "scrQuestions", "scrCompleted", "scrOverview", "scrSubmissions",
    # Phase 2 - role alignment accept/reject
    "scrAlignment", "scrRejection", "scrAlignLocked",
]


def block(name):
    lines = open(os.path.join(SRC, name + ".pa.yaml")).read().split("\n")
    out, started = [], False
    for ln in lines:
        if not started:
            # the screen's own `    Children:` - 4 spaces, not deeper
            if ln.startswith("    Children:") and not ln.startswith("     "):
                started = True
            continue
        s = ln.strip()
        if s == "" or s.startswith("#"):
            continue
        out.append(ln[6:] if ln.startswith("      ") else ln)
    return "\n".join(out).rstrip() + "\n"


def onselect(screen, control):
    """The OnSelect formula of `control` on `screen`, dedented, '=' stripped."""
    lines = open(os.path.join(SRC, screen + ".pa.yaml")).read().split("\n")
    i = next(k for k, ln in enumerate(lines) if ln.strip() == "- %s:" % control)
    j = next(k for k in range(i, len(lines)) if lines[k].strip().startswith("OnSelect:"))
    if lines[j].strip() != "OnSelect: |-":
        return lines[j].split("OnSelect: =", 1)[1]
    base = len(lines[j + 1]) - len(lines[j + 1].lstrip())
    out = []
    for ln in lines[j + 1:]:
        if ln.strip() and len(ln) - len(ln.lstrip()) < base:
            break
        out.append(ln[base:])
    return "\n".join(out).rstrip()[1:]


ADMIN_REBUILD_HEADER = """/* =============================================================================
   ADMIN DATA BUILD  (GENERATED by tools/gen_paste.py - edit Src, not this file)
   The OnSelect of btnRefreshOverview (scrOverview) and btnRefreshSubs
   (scrSubmissions). Both buttons carry exactly this text; each screen's
   OnVisible presses its button with Select(). Leading '=' already removed.

   Admins get every row on People; a line manager only the rows whose
   LineManagerEmail is their own (lower-case) address. Needs the
   LineManagerEmail column on 'RolePreference People' and all six tables.
   ============================================================================ */
"""


def main():
    names = sys.argv[1:] or SCREENS
    for name in names:
        text = block(name)
        with open(os.path.join(OUT, name + ".controls.yaml"), "w") as fh:
            fh.write(text)
        print(f"wrote {name}.controls.yaml ({len(text)} bytes)")
    text = ADMIN_REBUILD_HEADER + onselect("scrOverview", "btnRefreshOverview") + "\n"
    with open(os.path.join(OUT, "admin-rebuild.powerfx"), "w") as fh:
        fh.write(text)
    print(f"wrote admin-rebuild.powerfx ({len(text)} bytes)")


if __name__ == "__main__":
    main()
