#!/usr/bin/env python3
"""
Generate paste/<screen>.controls.yaml from Src/<screen>.pa.yaml.

Power Apps Studio's Code View paste expects a TOP-LEVEL LIST OF CONTROLS on the
clipboard, not the `Screens:` document that .pa.yaml (pack/unpack) format uses.
This strips the wrapper and normalises the result to what the deserializer
accepts:

  Src/scrX.pa.yaml                     paste/scrX.controls.yaml
  --------------------------------     -------------------------------
  Screens:                             - conRoot:
    scrX:                                  Control: GroupContainer@1.5.0
      Properties:            ---->         ...
        Fill: =...                     - conSomeOverlay:
      Children:                            ...
        - conRoot:
            Control: ...

Three transformations, all required:

  1. Drop everything up to and including the screen's `Children:` line. Screen
     PROPERTIES (Fill, OnVisible) are NOT carried by a control paste - they must
     be set by hand in Studio. See paste/HOW-TO-PASTE.md.
  2. Dedent by 6 spaces so the first control sits at column 0.
  3. Strip `#` comments and blank lines. Studio's YAML parser rejects them with
     `PA1001 ... YamlInvalidSyntax`. The Src files keep their comments for Git.

It also writes paste/admin-rebuild.powerfx: the admin data build, lifted
from btnRefreshOverview.OnSelect on scrOverview (btnRefreshSubs on
scrSubmissions carries the same text - tools/scan_paste.py checks). Use it
if either button's formula ever has to be re-pasted by hand.

And it writes paste/test-app/: a copy of every paste file that names the
Preferences or PreferenceResponses table, with those names suffixed _1. The
Phase 2 test app has each of those two tables bound twice and its formulas
use the _1 bindings, so the plain files show "name isn't valid" there.
Removing the duplicate data sources and re-adding each table once makes the
plain files work and this folder unnecessary.

Usage:  python3 tools/gen_paste.py scrLanding
        python3 tools/gen_paste.py            # all screens
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "Src")
OUT = os.path.join(ROOT, "paste")

SCREENS = [
    "scrLanding", "scrForm", "scrDetail", "scrReview",
    "scrQuestions", "scrCompleted", "scrOverview", "scrSubmissions",
    # Phase 2 - role alignment accept/reject
    "scrAlignment", "scrRejection", "scrAlignLocked",
]


def block(name):
    lines = open(os.path.join(SRC, name + ".pa.yaml")).read().split("\n")
    out, started = [], False
    for ln in lines:
        if not started:
            # the screen's own `    Children:` - 4 spaces, not deeper
            if ln.startswith("    Children:") and not ln.startswith("     "):
                started = True
            continue
        s = ln.strip()
        if s == "" or s.startswith("#"):
            continue
        out.append(ln[6:] if ln.startswith("      ") else ln)
    return "\n".join(out).rstrip() + "\n"


def onselect(screen, control):
    """The OnSelect formula of `control` on `screen`, dedented, '=' stripped."""
    lines = open(os.path.join(SRC, screen + ".pa.yaml")).read().split("\n")
    i = next(k for k, ln in enumerate(lines) if ln.strip() == "- %s:" % control)
    j = next(k for k in range(i, len(lines)) if lines[k].strip().startswith("OnSelect:"))
    if lines[j].strip() != "OnSelect: |-":
        return lines[j].split("OnSelect: =", 1)[1]
    base = len(lines[j + 1]) - len(lines[j + 1].lstrip())
    out = []
    for ln in lines[j + 1:]:
        if ln.strip() and len(ln) - len(ln.lstrip()) < base:
            break
        out.append(ln[base:])
    return "\n".join(out).rstrip()[1:]


ADMIN_REBUILD_HEADER = """/* =============================================================================
   ADMIN DATA BUILD  (GENERATED by tools/gen_paste.py - edit Src, not this file)
   The OnSelect of btnRefreshOverview (scrOverview) and btnRefreshSubs
   (scrSubmissions). Both buttons carry exactly this text; each screen's
   OnVisible presses its button with Select(). Leading '=' already removed.

   Admins get every row on People; a line manager only the rows whose
   LineManagerEmail is their own (lower-case) address. Needs the
   LineManagerEmail column on 'RolePreference People' and all six tables.
   ============================================================================ */
"""


TEST_APP = os.path.join(OUT, "test-app")
SUFFIX = {
    "'RolePreference PreferenceResponses'": "'RolePreference PreferenceResponses_1'",
    "'RolePreference Preferences'": "'RolePreference Preferences_1'",
}
# Phase 1 is retired; its frozen OnStart is not needed in the test app.
TEST_APP_SKIP = {"App_OnStart.phase1.powerfx"}


def to_test_app(text):
    for old, new in SUFFIX.items():
        text = text.replace(old, new)
    return text


def write_test_app():
    os.makedirs(TEST_APP, exist_ok=True)
    for f in os.listdir(TEST_APP):
        os.remove(os.path.join(TEST_APP, f))
    made = []
    for f in sorted(os.listdir(OUT)):
        path = os.path.join(OUT, f)
        if f in TEST_APP_SKIP or not os.path.isfile(path):
            continue
        if not (f.endswith(".controls.yaml") or f.endswith(".powerfx")):
            continue
        text = open(path).read()
        if not any(old in text for old in SUFFIX):
            continue
        with open(os.path.join(TEST_APP, f), "w") as fh:
            fh.write(to_test_app(text))
        made.append(f)
    rows = "\n".join(f"| `{f}` | `../{f}` |" for f in made)
    readme = f"""# Paste files for the Phase 2 TEST app (`_1` table names)

GENERATED by `tools/gen_paste.py` - do not edit; edit `Src/` or the file in
`paste/`, then regenerate.

The test app has `RolePreference Preferences` and `RolePreference
PreferenceResponses` bound twice, and its formulas use the `_1` bindings
(`'RolePreference Preferences_1'`, `'RolePreference PreferenceResponses_1'`),
which carry the current schema. The plain files in `paste/` use the names
without `_1`, so in the test app they show *"Name isn't valid"*.

**Use the file from this folder when it exists; otherwise use the one in
`paste/` as it is** - every other file names neither table, so it is the same
in both apps. People, Roles, Eligibilities and Alignments are never suffixed.

| This folder | Same as, with `_1` names |
|---|---|
{rows}

Copy from GitHub (open the file, then **Copy raw file**), not from a chat
window - a partial copy pastes a half-empty screen with no error.

To retire this folder: in the test app remove BOTH data-source entries for each
of the two tables and add each table back once. The plain files then work.
"""
    with open(os.path.join(TEST_APP, "README.md"), "w") as fh:
        fh.write(readme)
    print(f"wrote test-app/ ({len(made)} files)")


def main():
    names = sys.argv[1:] or SCREENS
    for name in names:
        text = block(name)
        with open(os.path.join(OUT, name + ".controls.yaml"), "w") as fh:
            fh.write(text)
        print(f"wrote {name}.controls.yaml ({len(text)} bytes)")
    text = ADMIN_REBUILD_HEADER + onselect("scrOverview", "btnRefreshOverview") + "\n"
    with open(os.path.join(OUT, "admin-rebuild.powerfx"), "w") as fh:
        fh.write(text)
    print(f"wrote admin-rebuild.powerfx ({len(text)} bytes)")
    write_test_app()


if __name__ == "__main__":
    main()
